version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "${APP_PORT}:8080"
    environment:
      NODE_ENV: production
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    command: node dist/main.js
    depends_on:
      - mariadb
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      NODE_ENV: production
    command: npx serve -s dist
    depends_on:
      - server
