FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

# RUN mkdir -p -v ExcelUploads ExcelPending

EXPOSE 8080 9229

CMD ["nodemon", "--watch", "src", "--exec", "node", "--inspect=0.0.0.0:9229", "dist/main.js"]