FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm install -g nodemon

RUN mkdir -p /app/ExcelUploads /app/ExcelPending

EXPOSE 8080 9229

CMD ["nodemon", "--watch", "src", "--exec", "node", "--inspect=0.0.0.0:9229", "dist/main.js"]